force-app/main/default/objects/Error_Log__c/fields/Log_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Log_Date_Time__c</fullName>
    <description>(Store the Date &amp; Time details when the Error Occurred</description>
    <label>Log Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Log_Details__c.field-meta.xml
<CustomField>
    <fullName>Log_Details__c</fullName>
    <description>(Stores the Complete Stack Track about the Problem)</description>
    <label>Log Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>The Name of Either Apex Class or Apex Trigger</description>
    <label>Process Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/maxfiterrorclass.cls
public class maxfiterrorclass {
    public static void logError( String logDetails, String processName)
    {
        Error_Log__c err = new Error_Log__c();
         err.Log_Date_Time__c = DATETIME.NOW();
         err.Log_Details__c = logDetails;
         err.Process_Name__c = processName;
         try {
            insert err;
        } catch (DmlException e) {
            System.debug('Error inserting Error Log record: ' + e.getMessage());
        }

    }

 


}