force-app/main/default/objects/Error_Log__c/fields/Log_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Log_Date_Time__c</fullName>
    <description>(Store the Date &amp; Time details when the Error Occurred</description>
    <label>Log Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Log_Details__c.field-meta.xml
<CustomField>
    <fullName>Log_Details__c</fullName>
    <description>(Stores the Complete Stack Track about the Problem)</description>
    <label>Log Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>The Name of Either Apex Class or Apex Trigger</description>
    <label>Process Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExceptionHandlingTest.cls
@isTest
public class ExceptionHandlingTest {
    @isTest
    static void testExceptionMethod() {
        String logDetails = 'Test log details';
        String processName = 'Test process name';
        Test.startTest();
        maxfiterrorclass.logError(logDetails, processName);
        Test.stopTest();
        List<Error_Log__c> logs = [SELECT Log_Date_Time__c, Log_Details__c, Process_Name__c FROM Error_Log__c WHERE Process_Name__c = :processName];
        System.assertEquals(1, logs.size(), 'There should be one log record');
    }
    @isTest
    static void testExceptionMethodWithException() {
        String logDetails = null;
        String processName = 'Test process name with exception';
        Test.startTest();
        maxfiterrorclass.logError(logDetails, processName);
        Test.stopTest();
        List<Error_Log__c> logs = [SELECT Log_Date_Time__c, Log_Details__c, Process_Name__c FROM Error_Log__c WHERE Process_Name__c = :processName];
        System.assertEquals(0, logs.size(), 'There should be no log record due to exception');
    }
}