force-app/main/default/objects/Attendees__c/Attendees__c.object-meta.xml
<CustomObject>
    <label>Attendees</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendeess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendees__c/fields/Locationn__c.field-meta.xml
<CustomField>
    <fullName>Locationn__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location(Addressbook)</label>
    <referenceTo>LocationAddressbook__c</referenceTo>
    <relationshipLabel>Attendeess</relationshipLabel>
    <relationshipName>Attendeess</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Organizer</label>
    <referenceTo>EventOrgainizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Locationn__c.field-meta.xml
<CustomField>
    <fullName>Locationn__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location(Addressbook)</label>
    <referenceTo>LocationAddressbook__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Attendees__c.field-meta.xml
<CustomField>
    <fullName>Attendees__c</fullName>
    <label>Attendees</label>
    <referenceTo>Attendees__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EventOrgainizer__c/EventOrgainizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LocationAddressbook__c/LocationAddressbook__c.object-meta.xml
<CustomObject>
    <label>Location(Addressbook)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LocationAddressbook__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MaxFitEmailTriggerHandler.cls
public class MaxFitEmailTriggerHandler {
    public static void sendEmailNotification(List<Event_Attendee__c> EventAttendeeList)
    {
          List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
          Set<Id> attendeeIds = new Set<Id>();
 
        for (Event_Attendee__c myEvent : EventAttendeeList) {
            if (myEvent.Attendees__c != null) {
                attendeeIds.add(myEvent.Attendees__c);
            }
        }
        Map<Id, Attendees__c> attendeeMap = new Map<Id, Attendees__c>([
            SELECT Id, Name,E_mail__c FROM Attendees__c WHERE Id IN :attendeeIds
        ]);
 
        Set<Id> eventIds = new Set<Id>();
        for (Event_Attendee__c myEvent : EventAttendeeList) {
            if (myEvent.Event__c != null) {
                eventIds.add(myEvent.Event__c);
            }
        }
        Map<Id, Event__c> eventMap = new Map<Id, Event__c>([
            SELECT Id, Name__c, Start__c, Locationn__c, Event_Organizer__c FROM Event__c WHERE Id IN :eventIds
        ]);
 
        for (Event_Attendee__c myEvent : EventAttendeeList) {
            Attendees__c attendee = attendeeMap.get(myEvent.Attendees__c);
            Event__c event = eventMap.get(myEvent.Event__c);
 
            if (attendee != null && attendee.E_mail__c != null && event != null) {
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                List<String> sendTo = new List<String>();
                sendTo.add(attendee.E_mail__c);
                mail.setToAddresses(sendTo);
                mail.setSubject('Pass for the ' + event.Name__c);
                String body = 'Dear ' + attendee.Name + ',<br/>';
                List<LocationAddressbook__c> l1 = [SELECT Name, State__c, Country__c from LocationAddressbook__c where Id =: event.Locationn__c];
 body += 'Thank you for registering for ' + event.Name__c + ' which will be organized on ' + event.Start__c + ' & will be held in ' + l1[0].Name + '. We are excited to have you, see you at the event.'+'<br/>';
                body += 'Thanks,'+'<br/>';
                List<EventOrgainizer__c> temp=[SELECT Name from EventOrgainizer__c where Id =: event.Event_Organizer__c];
                body += temp[0].Name;
                mail.setHtmlBody(body);
 
                mails.add(mail);
 
                System.debug('Email created for: ' + attendee.E_mail__c);
            } else {
                System.debug('Attendee or Event is null for Event_Attendee__c Id: ' + myEvent.Id);
            }
        }
        if (!mails.isEmpty()) {
            Messaging.sendEmail(mails);
            System.debug('Emails sent: ' + mails.size());
        } else {
            System.debug('No emails to send.');
        }
    }
    }